[package]
name = "who-fic-icf"
description = "World Health Organization (WHO) International Classification of Functioning, Disability and Health (ICF)"
keywords = ["who", "icf", "health", "disability", "functioning"]
categories = ["science", "parser-implementations"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
