[package]
name = "who-fic-icf"
description = "World Health Organization (WHO) International Classification of Functioning, Disability and Health (ICF)"
keywords = ["who", "icf", "health", "disability", "functioning"]
categories = ["science", "parser-implementations"]
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
serde = { version = "1.0.229", features = ["derive"], optional = true }

[features]
serde = ["dep:serde"]

[dev-dependencies]
proptest = "1.11.0"
serde_json = "1.0"
