[package]
name = "who-fic-icd"
description = "World Health Organization (WHO) International Classification of Diseases (ICD)"
keywords = ["who", "icd", "icd10", "icd11", "health"]
categories = ["science", "parser-implementations"]
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
serde = { version = "1.0.229", features = ["derive"], optional = true }
who-fic-claml = { workspace = true, optional = true }
who-fic-linearization = { workspace = true, optional = true }

[features]
serde = ["dep:serde"]
claml = ["dep:who-fic-claml"]
linearization = ["dep:who-fic-linearization"]

[dev-dependencies]
proptest = "1.11.0"
serde_json = "1.0"
